name: iac_device_info_ext
description: "Device information extension for in_app_console package. Display device details and system information in the console."
version: 1.0.0
repository: https://github.com/mduccc/in_app_console/tree/main/packages/iac_device_info_ext

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  in_app_console: ^2.0.2
  device_info_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.iac_device_info_ext
        pluginClass: IacDeviceInfoExtPlugin
      ios:
        pluginClass: IacDeviceInfoExtPlugin
